swagger: "2.0"
info:
  title: YouTube API
  description: This is Description
  version: 1.0
  contact:
    email: kishan.p@simformsolutions.com
  license: 
    name: Apache 2.0
    url: "http://apache.org/"
  servers:
    -url: "http://localhost:3000/"
    description: "This is Local Server"

    
  schemes : [http,https]