swagger: "2.0"
info:
  title: Task Manager API
  description: This is Description of API for Task Manager App
  version: 1.0
  contact:
    email: kishan.p@simformsolutions.com
  license: 
    name: Apache 2.0
    url: "http://apache.org/"
  servers:
    -url: "http://localhost:3000/"
    description: "This is Local Server"
  components:
      securitySchemes:
        bearerAuth:          
         type: http
          scheme: bearer
          bearerFormat: JWT    
          
  schemes : [http,https]

paths:
#Users
  /users:
  # Create Users
    post: 
      summary: Create New Users
      description: This API creates new users
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          email: body
          password: body
      responses:
        '200':
          description: OK
    # Get All Users
    get:
      summary: Returns list of all Users
      description: This API returns list of all users      
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          schema:
            type: String
            example: "Users List"